### PR TITLE
Update deprecated syntax in SiftClient.php

### PR DESCRIPTION
**Pull request by TheLevti**
## Purpose

- Support of newest php versions.

## Summary

- With newest php version this causes a lot of deprecation notices. Please use correct syntax from now on.

## Checklist

- [x] The change was thoroughly tested manually

### CODE REVIEW

**Comment by TheLevti** [comment]
Solves https://github.com/SiftScience/sift-php/issues/96

**Comment by TheLevti** [comment]
Many of us would be very thankful if this gets released asap as this deprecation warning generates tons of unnecessary logs throughout systems.

**Comment by viaskal-sift** [comment]
@TheLevti thanks for raising this, we will review and release it soon

**Comment by viaskal-sift** [comment]
@TheLevti we already merged some changes to the master after you created your PR - could you pls update from branch from the master so that it is up-to-date and we can proceed with merging?

**Comment by TheLevti** [comment]
> @TheLevti we already merged some changes to the master after you created your PR - could you pls update from master so that it is up-to-date and we can proceed with merging?

Done

**Pull request merged**
